Updated panda description
KavrakiLab/robowflex_resources pull request #7
Opened 2021-05-21 22:23 UTC by cinephilia-z

This PR updates the panda description & moveit config. Before this, the collision geometry is a cylinder/sphere encasing the hand. The collision area might be too big and the panda hand could not get close to certain object (for example, when we want the robot to grasp a can). Most of the files are copied from moveit_resources package. 

https://github.com/ros-planning/moveit_resources/tree/master/panda_description
https://github.com/ros-planning/moveit_resources/tree/master/panda_moveit_config

2021-05-21 22:52 UTC, zkingston commented
Please double check which files are still needed in the description (the xacro URDF/SRDF files in particular). Remove them if they are no longer needed. Also, please open a pull to update [resources_visualization.cpp](https://github.com/KavrakiLab/robowflex/blob/master/robowflex_library/scripts/resources_visualization.cpp) in the main Robowflex library so the script properly loads the Panda. Also double check which geometry files (the new STLs + the modifications to the existing DAE) are required.

2021-05-21 23:29 UTC, cinephilia-z commented
Thx for the reminder! I just deleted the unused xacro urdf/srdf and also updated the panda.yml file.

2021-05-22 03:34 UTC, ChamzasKonstantinos requested changes
I marked some other files that you need to delete as well since they are not needed

2021-05-22 03:34 UTC, ChamzasKonstantinos commented on panda/config/cartesian_limits.yaml
> +cartesian_limits:
Delete file

2021-05-22 03:34 UTC, ChamzasKonstantinos commented on panda/config/fake_controllers.yaml
> +controller_list:
Delete File

2021-05-22 03:34 UTC, ChamzasKonstantinos commented on panda/config/panda_controllers.yaml
> + controller_list:
Delete File

2021-05-22 03:34 UTC, ChamzasKonstantinos commented on panda/config/panda_gripper_controllers.yaml
> +  - name: position_joint_trajectory_controller
Delete File

2021-05-22 03:34 UTC, ChamzasKonstantinos commented on panda/config/sensors_kinect_depthmap.yaml
> +    image_topic: /camera/depth_registered/image_raw
Delete File

2021-05-22 03:34 UTC, ChamzasKonstantinos commented on panda/config/sensors_kinect_pointcloud.yaml
> +sensors:
Delete File

2021-05-22 03:37 UTC, ChamzasKonstantinos commented on panda.yml
> +limits: "package://robowflex_resources/panda/config/joint_limits.yaml"
This should be ``joint_limits``

2021-05-22 16:28 UTC, zkingston commented on panda.yml
> +urdf: "package://robowflex_resources/panda/panda_description/urdf/panda.urdf"
This should follow the prior naming scheme where the urdf is in the "urdf" directory, not the "panda_description" directory.

2021-05-24 23:30 UTC, cinephilia-z commented
this is screenshots of running `rosrun robowflex_library resources_visualization panda`
<img width="896" alt="panda_rviz" src="https://user-images.githubusercontent.com/46663611/119418632-080fe680-bcbe-11eb-8896-42e18f1648da.png">
<img width="518" alt="Screenshot 2021-05-24 181857" src="https://user-images.githubusercontent.com/46663611/119418648-1100b800-bcbe-11eb-8cf7-15b597b3b7a3.png">

2021-05-24 23:32 UTC, ChamzasKonstantinos approved these changes
LGTM!

2021-05-25 00:36 UTC, merged