Adding High-Dimensional Manipulator (Shadowhand mounted on KUKA LWR)
KavrakiLab/robowflex_resources pull request #8
Opened 2021-05-27 16:48 UTC by aorthey

This PR adds the Shadowhand by Shadow Robotics. It is currently mounted on a KUKA LWR Robot. 

Only tested with the visualization script so far. I'll probably need to add some additonal updates when testing on the scenarios.

![Screenshot from 2021-05-27 18-44-44](https://user-images.githubusercontent.com/1220541/119865225-bd8ba580-bf1b-11eb-81d4-250dbaf19437.png)
![Screenshot from 2021-05-27 18-44-55](https://user-images.githubusercontent.com/1220541/119865227-be243c00-bf1b-11eb-8736-2fe79cff9407.png)

2021-05-27 18:56 UTC, ChamzasKonstantinos requested changes
I think this is almost everything we need. 
To do planning we would need 2 more files the kinematics.yaml that specifies which IK solvers to use for which planning group and the ompl_planning.yaml config file that tells us which planners are available for which group similar to [here](https://github.com/KavrakiLab/robowflex_resources/tree/master/baxter/config) or here   [here](https://github.com/KavrakiLab/robowflex_resources/tree/master/fetch/config)

2021-05-28 11:05 UTC, aorthey commented
Thanks @ChamzasKonstantinos. I have added the missing files. I just tried to set up the IK solver (i.e. using the generate.sh script on the table environment), but I am not sure how I can make it rotation-independent or fix a particular orientation. The issue is basically that the IK solver always uses the orientation in the picture below and then fails finding solutions. Is there anyway I can change that? 

![Screenshot from 2021-05-28 12-59-10](https://user-images.githubusercontent.com/1220541/119974752-5a4e5180-bfb5-11eb-9311-470d1ad7b418.png)

2021-05-28 15:51 UTC, zkingston commented
If there is a source repository for this robot, can you add a link to the README? Also, can you add an initializer YAML like [this one](https://github.com/KavrakiLab/robowflex_resources/blob/master/fetch.yml)?

2021-06-21 15:41 UTC, zkingston approved these changes

2021-06-21 15:41 UTC, merged